# Generated by Django 6.1.1 on 2026-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='date_range_es',
            field=models.CharField(blank=True, help_text='e.g. Marzo 2020 - Abril 2026', max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_es',
            field=models.TextField(blank=True, help_text='Spanish translation, one bullet point per line. Falls back to English if blank.'),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_es',
            field=models.CharField(blank=True, help_text='Spanish translation. Falls back to English if blank.', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(blank=True, help_text='Spanish translation. Falls back to English if blank.'),
        ),
    ]
